name: flutter_study
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/dessert/canoli.jpg
    - assets/images/dessert/brownie_cheesecake.jpeg
    - assets/images/dessert/carrot_cake.jpg
    - assets/images/dessert/choco-cake.jpg
    - assets/images/dessert/lemon-cream-cake.jpg
    - assets/images/dessert/raspberry_cake.jpg
    - assets/images/dessert/tiramisu.jpg
    - assets/images/starters/triopitaki.jpg
    - assets/images/starters/cheese_plate.jpg
    - assets/images/starters/garlic_bread.jpg
    - assets/images/starters/grilled_mushrooms.jpeg
    - assets/images/starters/onion_rings.jpg
    - assets/images/salads/chicken_ceasar.jpg
    - assets/images/salads/greek_salad.jpg
    - assets/images/salads/potato_salad.jpg
    - assets/images/soups/beetroot_soup.jpg
    - assets/images/soups/onion_soup.jpg
    - assets/images/soups/pumpkin_soup.jpg
    - assets/images/main_course/bangers_mash.jpg
    - assets/images/main_course/cottage_pie.jpg
    - assets/images/main_course/kotlet-devolay.jpg
    - assets/images/main_course/lancashire_hotpot.jpg
    - assets/images/warm_beverages/americano.jpg
    - assets/images/warm_beverages/cappuccino.jpg
    - assets/images/warm_beverages/espresso.jpg
    - assets/images/warm_beverages/hot-chocolate.jpg
    - assets/images/warm_beverages/macchiato_1.jpg
    - assets/images/cold_beverages/coca_cola.jpg
    - assets/images/cold_beverages/nestea.jpg
    - assets/images/cold_beverages/sprite.jpg
    - assets/images/cold_beverages/fresh.jpg

  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
